import { JobRole } from '@/types'

export const MOCK_ROLES: JobRole[] = [
  {
    id: 'role-1',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    description: 'We are looking for a Senior Frontend Engineer with strong React and TypeScript skills.',
    candidateCount: 4,
    avgScore: 81,
    status: 'active',
    createdAt: '2025-01-10',
    candidates: [
      {
        id: 'c1',
        name: 'Ahmed Al-Rashid',
        initials: 'AA',
        color: '#f0a500',
        role: 'Senior Frontend Engineer',
        background: 'traditional',
        status: 'assessed',
        email: 'ahmed@example.com',
        githubUrl: 'https://github.com',
        linkedinUrl: 'https://linkedin.com',
        portfolioUrl: 'https://portfolio.com',
        scores: { resume: 88, github: 92, linkedin: 75, portfolio: 85 },
        overall: 87,
      },
      {
        id: 'c2',
        name: 'Sarah Chen',
        initials: 'SC',
        color: '#00c8d4',
        role: 'Senior Frontend Engineer',
        background: 'bootcamp',
        status: 'assessed',
        email: 'sarah@example.com',
        githubUrl: 'https://github.com',
        portfolioUrl: 'https://portfolio.com',
        scores: { resume: 72, github: 95, linkedin: 68, portfolio: 90 },
        overall: 84,
      },
      {
        id: 'c3',
        name: 'James Okafor',
        initials: 'JO',
        color: '#00d68f',
        role: 'Senior Frontend Engineer',
        background: 'traditional',
        status: 'assessed',
        email: 'james@example.com',
        linkedinUrl: 'https://linkedin.com',
        scores: { resume: 91, github: 78, linkedin: 88, portfolio: 70 },
        overall: 83,
      },
      {
        id: 'c4',
        name: 'Priya Sharma',
        initials: 'PS',
        color: '#ff4d6d',
        role: 'Senior Frontend Engineer',
        background: 'traditional',
        status: 'pending',
        email: 'priya@example.com',
        githubUrl: 'https://github.com',
        scores: { resume: 85, github: 80, linkedin: 82, portfolio: 78 },
        overall: 81,
      },
    ],
  },
  {
    id: 'role-2',
    title: 'ML Engineer',
    department: 'AI Research',
    description: 'Seeking an ML Engineer with experience in PyTorch, LangChain and production AI systems.',
    candidateCount: 3,
    avgScore: 74,
    status: 'active',
    createdAt: '2025-01-14',
    candidates: [
      {
        id: 'c5',
        name: 'Lucas Mendes',
        initials: 'LM',
        color: '#a78bfa',
        role: 'ML Engineer',
        background: 'self-taught',
        status: 'assessed',
        email: 'lucas@example.com',
        githubUrl: 'https://github.com',
        portfolioUrl: 'https://portfolio.com',
        scores: { resume: 65, github: 88, linkedin: 60, portfolio: 82 },
        overall: 76,
      },
      {
        id: 'c6',
        name: 'Fatima Al-Zahra',
        initials: 'FA',
        color: '#f472b6',
        role: 'ML Engineer',
        background: 'traditional',
        status: 'assessed',
        email: 'fatima@example.com',
        linkedinUrl: 'https://linkedin.com',
        scores: { resume: 78, github: 70, linkedin: 74, portfolio: 76 },
        overall: 74,
      },
      {
        id: 'c7',
        name: 'Tom Whitfield',
        initials: 'TW',
        color: '#fb923c',
        role: 'ML Engineer',
        background: 'bootcamp',
        status: 'pending',
        email: 'tom@example.com',
        githubUrl: 'https://github.com',
        scores: { resume: 60, github: 82, linkedin: 55, portfolio: 88 },
        overall: 72,
      },
    ],
  },
  {
    id: 'role-3',
    title: 'Backend Engineer',
    department: 'Engineering',
    description: 'Looking for a Backend Engineer with Node.js, Python and cloud infrastructure experience.',
    candidateCount: 2,
    avgScore: 69,
    status: 'active',
    createdAt: '2025-01-18',
    candidates: [
      {
        id: 'c8',
        name: 'Yuna Park',
        initials: 'YP',
        color: '#34d399',
        role: 'Backend Engineer',
        background: 'traditional',
        status: 'assessed',
        email: 'yuna@example.com',
        linkedinUrl: 'https://linkedin.com',
        scores: { resume: 70, github: 65, linkedin: 72, portfolio: 60 },
        overall: 67,
      },
      {
        id: 'c9',
        name: 'Omar Hassan',
        initials: 'OH',
        color: '#60a5fa',
        role: 'Backend Engineer',
        background: 'traditional',
        status: 'pending',
        email: 'omar@example.com',
        githubUrl: 'https://github.com',
        scores: { resume: 74, github: 68, linkedin: 70, portfolio: 65 },
        overall: 70,
      },
    ],
  },
]

export const ALL_CANDIDATES = MOCK_ROLES.flatMap(r => r.candidates)